# Generated by Django 4.1.3 on 2022-11-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='wallets',
            field=models.JSONField(null=True, verbose_name='Wallets'),
        ),
    ]
