# Generated by Django 4.1.3 on 2022-11-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_wallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='wallets',
            field=models.JSONField(default='{}', verbose_name='Wallets'),
        ),
    ]
