# Generated by Django 4.1.3 on 2022-11-14 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deals',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Сделки'),
            preserve_default=False,
        ),
    ]
