# Generated by Django 4.1.3 on 2022-11-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.IntegerField(default=1, verbose_name='Заявки'),
        ),
    ]
