# Generated by Django 4.1.3 on 2022-11-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='condition',
            field=models.BooleanField(default=False, verbose_name='condition'),
        ),
    ]
