# Generated by Django 4.1.3 on 2022-11-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainInfo',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер счета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.IntegerField(default=0, verbose_name='Заявки'),
        ),
    ]
