# Generated by Django 4.1.3 on 2022-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_maininfo_user_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200, verbose_name='Валюта')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('sign', models.CharField(max_length=200, verbose_name='Типографский знак')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
