# Generated by Django 4.1.3 on 2022-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exchangerates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='lifespan',
        ),
        migrations.AddField(
            model_name='request',
            name='requisites',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='wallets',
            field=models.JSONField(default='{}', verbose_name='Реквизиты пользователя'),
        ),
    ]
