# Generated by Django 4.1.3 on 2022-11-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_request_user_alter_request_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.user'),
        ),
    ]
